"""Train and distill the offline ML base TVT predictor (SOT-2393).

Trains a numpy gradient-boosted regression tree on the local train wells and
writes the distilled model (parallel node arrays) into the ``_MODEL_JSON`` block
of both ``src/ml_predictor.py`` and ``kaggle/rogii-claude-baseline.py`` so the two
entry points stay byte-identical.

To keep the toe-holdout confirm gate leak-free, the shipped model is trained on
train wells **outside** the evaluation hold-out fold (``holdout_wells(train,5,0)``);
those hold-out wells are exactly the ones ``src.evaluate`` scores the predictor on.

Usage::

    python3 scripts/train_ml_predictor.py --train-dir data/raw/train
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import time
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from src.data import load_horizontal, load_typewell  # noqa: E402
from src.evaluate import TEST_HEEL_FRACTION, holdout_wells  # noqa: E402
from src.ml_predictor import (  # noqa: E402
    FEATURE_NAMES,
    _column,
    _typewell_signature,
    extract_toe_features,
)

SRC_MODULE = REPO_ROOT / "src" / "ml_predictor.py"
KERNEL = REPO_ROOT / "kaggle" / "rogii-claude-baseline.py"
BEGIN = "# === BEGIN ML_MODEL_JSON (generated by scripts/train_ml_predictor.py) ==="
END = "# === END ML_MODEL_JSON ==="
CODE_BEGIN = "# === BEGIN ML_SHARED_CODE (synced verbatim into kaggle/rogii-claude-baseline.py) ==="
CODE_END = "# === END ML_SHARED_CODE ==="

MAX_ROWS_PER_WELL = 300
RNG_SEED = 20393


def _heel_count(n_rows: int) -> int:
    return max(1, min(n_rows - 1, round(n_rows * TEST_HEEL_FRACTION)))


def build_training_matrix(train_dir: Path, wells: list[str]):
    """Assemble (X, y) from the toe rows of the given wells, mirroring evaluation."""
    xs: list[np.ndarray] = []
    ys: list[np.ndarray] = []
    used_wells = 0
    for well in wells:
        horizontal_path = train_dir / f"{well}__horizontal_well.csv"
        typewell_path = train_dir / f"{well}__typewell.csv"
        if not horizontal_path.is_file() or not typewell_path.is_file():
            continue
        rows = load_horizontal(horizontal_path, require_target=True)
        typewell = load_typewell(typewell_path)
        heel = _heel_count(len(rows))
        # Mirror the toe-holdout mask: heel keeps TVT_input, toe hides it.
        masked = [
            dict(row, TVT_input=(row["TVT_input"] if i < heel else ""))
            for i, row in enumerate(rows)
        ]
        md = _column(masked, "MD")
        z = _column(masked, "Z")
        x = _column(masked, "X")
        y = _column(masked, "Y")
        gr = _column(masked, "GR")
        known_tvt = _column(masked, "TVT_input")
        if not np.isfinite(md).all() or not np.isfinite(known_tvt).any():
            continue
        try:
            tw_tvt, tw_gr = _typewell_signature(typewell)
            feats, eval_idx, last_tvt, base_pred = extract_toe_features(
                md, z, x, y, gr, known_tvt, tw_tvt, tw_gr
            )
        except ValueError:
            continue
        if eval_idx.size == 0:
            continue
        truth = _column(rows, "TVT")[eval_idx]
        # The GBRT learns the residual over the offset-trend base prediction.
        target = truth - base_pred
        keep = np.isfinite(target)
        feats = feats[keep]
        target = target[keep]
        if feats.shape[0] == 0:
            continue
        if feats.shape[0] > MAX_ROWS_PER_WELL:
            stride = feats.shape[0] / MAX_ROWS_PER_WELL
            pick = (np.arange(MAX_ROWS_PER_WELL) * stride).astype(int)
            feats = feats[pick]
            target = target[pick]
        xs.append(feats)
        ys.append(target)
        used_wells += 1
    if not xs:
        raise RuntimeError("No training rows assembled")
    return np.concatenate(xs), np.concatenate(ys), used_wells


# --- Exact-greedy gradient-boosted regression trees (squared error) ---


class _Node:
    __slots__ = ("feature", "threshold", "left", "right", "value")

    def __init__(self):
        self.feature = -1
        self.threshold = 0.0
        self.left = None
        self.right = None
        self.value = 0.0


def _best_split(member, sort_idx, X, grad, min_leaf):
    """Return (feature, threshold, left_mask, right_mask) or None for a node."""
    idx = np.flatnonzero(member)
    n = idx.size
    if n < 2 * min_leaf:
        return None
    tot = float(grad[idx].sum())
    best_gain = -np.inf
    best = None
    for f in range(X.shape[1]):
        order = sort_idx[f][member[sort_idx[f]]]
        xs = X[order, f]
        g = grad[order]
        cs = np.cumsum(g)
        # candidate split after position k (k in [min_leaf, n-min_leaf]);
        # only where the sorted value strictly increases (distinct boundary).
        distinct = xs[:-1] < xs[1:]
        k = np.arange(1, n)
        valid = distinct & (k >= min_leaf) & (k <= n - min_leaf)
        if not valid.any():
            continue
        sum_left = cs[:-1]
        n_left = k.astype(float)
        sum_right = tot - sum_left
        n_right = n - k
        gain = np.where(
            valid,
            sum_left ** 2 / n_left + sum_right ** 2 / n_right,
            -np.inf,
        )
        j = int(np.argmax(gain))
        if gain[j] > best_gain:
            best_gain = float(gain[j])
            threshold = 0.5 * (xs[j] + xs[j + 1])
            best = (f, threshold, order)
    if best is None:
        return None
    f, threshold, _ = best
    left_mask = member & (X[:, f] <= threshold)
    right_mask = member & (X[:, f] > threshold)
    if int(left_mask.sum()) < min_leaf or int(right_mask.sum()) < min_leaf:
        return None
    return f, threshold, left_mask, right_mask


def _build_tree(X, grad, sort_idx, max_depth, min_leaf, member0):
    root = _Node()

    def grow(node, member, depth):
        node.value = float(grad[member].mean())
        if depth >= max_depth:
            return
        split = _best_split(member, sort_idx, X, grad, min_leaf)
        if split is None:
            return
        f, threshold, left_mask, right_mask = split
        node.feature = f
        node.threshold = threshold
        node.left = _Node()
        node.right = _Node()
        grow(node.left, left_mask, depth + 1)
        grow(node.right, right_mask, depth + 1)

    grow(root, member0, 0)
    return root


def _flatten(root, max_depth):
    feature: list[int] = []
    threshold: list[float] = []
    left: list[int] = []
    right: list[int] = []
    value: list[float] = []

    def visit(node) -> int:
        idx = len(feature)
        feature.append(-1)
        threshold.append(0.0)
        left.append(-1)
        right.append(-1)
        value.append(node.value)
        if node.feature >= 0 and node.left is not None:
            li = visit(node.left)
            ri = visit(node.right)
            feature[idx] = int(node.feature)
            threshold[idx] = float(node.threshold)
            left[idx] = li
            right[idx] = ri
        return idx

    visit(root)
    return {
        "feature": feature,
        "threshold": threshold,
        "left": left,
        "right": right,
        "value": value,
        "max_depth": int(max_depth),
    }


def train_gbrt(X, y, *, n_trees, learning_rate, max_depth, min_leaf, subsample=0.6):
    base = float(y.mean())
    pred = np.full(X.shape[0], base)
    sort_idx = [np.argsort(X[:, f], kind="stable") for f in range(X.shape[1])]
    rng = np.random.default_rng(RNG_SEED)
    n = X.shape[0]
    trees = []
    for _ in range(n_trees):
        grad = y - pred
        if subsample < 1.0:
            member0 = rng.random(n) < subsample
        else:
            member0 = np.ones(n, dtype=bool)
        root = _build_tree(X, grad, sort_idx, max_depth, min_leaf, member0)
        tree = _flatten(root, max_depth)
        # update predictions with this tree
        contrib = _predict_tree(tree, X)
        pred = pred + learning_rate * contrib
        trees.append(tree)
    return {
        "base": base,
        "learning_rate": float(learning_rate),
        "n_features": int(X.shape[1]),
        "feature_names": list(FEATURE_NAMES),
        "trees": trees,
    }


def _predict_tree(tree, X):
    feat = np.asarray(tree["feature"])
    thr = np.asarray(tree["threshold"], dtype=float)
    left = np.asarray(tree["left"])
    right = np.asarray(tree["right"])
    value = np.asarray(tree["value"], dtype=float)
    n = X.shape[0]
    node = np.zeros(n, dtype=np.int64)
    for _ in range(int(tree["max_depth"])):
        f = feat[node]
        internal = f >= 0
        if not internal.any():
            break
        col = np.where(internal, f, 0)
        go_right = X[np.arange(n), col] > thr[node]
        node = np.where(internal, np.where(go_right, right[node], left[node]), node)
    return value[node]


def _write_model_block(path: Path, model_json: str) -> None:
    text = path.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(BEGIN) + r".*?" + re.escape(END),
        re.DOTALL,
    )
    replacement = f'{BEGIN}\n_MODEL_JSON = r"""{model_json}"""\n{END}'
    new_text, count = pattern.subn(replacement, text)
    if count != 1:
        raise RuntimeError(f"Expected exactly one model block in {path}, found {count}")
    path.write_text(new_text, encoding="utf-8")


def _extract_shared_code() -> str:
    text = SRC_MODULE.read_text(encoding="utf-8")
    start = text.index(CODE_BEGIN)
    end = text.index(CODE_END) + len(CODE_END)
    return text[start:end]


def _sync_shared_code(shared: str) -> None:
    text = KERNEL.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(CODE_BEGIN) + r".*?" + re.escape(CODE_END),
        re.DOTALL,
    )
    new_text, count = pattern.subn(lambda _m: shared, text)
    if count != 1:
        raise RuntimeError(f"Expected exactly one shared-code block in {KERNEL}, found {count}")
    KERNEL.write_text(new_text, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Train the offline ML base predictor")
    parser.add_argument("--train-dir", type=Path, default=REPO_ROOT / "data/raw/train")
    parser.add_argument("--n-trees", type=int, default=100)
    parser.add_argument("--learning-rate", type=float, default=0.03)
    parser.add_argument("--max-depth", type=int, default=3)
    parser.add_argument("--min-leaf", type=int, default=500)
    parser.add_argument("--subsample", type=float, default=0.6)
    args = parser.parse_args()

    eval_wells = holdout_wells(args.train_dir, 5, 0)
    all_wells = sorted(
        p.name[: -len("__horizontal_well.csv")]
        for p in args.train_dir.glob("*__horizontal_well.csv")
    )
    train_wells = [w for w in all_wells if w not in eval_wells]
    print(
        f"train wells: {len(train_wells)} (excluded {len(eval_wells)} eval hold-out)",
        flush=True,
    )

    t0 = time.time()
    X, y, used = build_training_matrix(args.train_dir, train_wells)
    print(f"assembled {X.shape[0]} rows x {X.shape[1]} feats from {used} wells "
          f"in {time.time() - t0:.1f}s", flush=True)

    t0 = time.time()
    model = train_gbrt(
        X, y,
        n_trees=args.n_trees,
        learning_rate=args.learning_rate,
        max_depth=args.max_depth,
        min_leaf=args.min_leaf,
        subsample=args.subsample,
    )
    fit_pred = np.full(X.shape[0], model["base"])
    for tree in model["trees"]:
        fit_pred = fit_pred + model["learning_rate"] * _predict_tree(tree, X)
    train_rmse = float(np.sqrt(np.mean((fit_pred - y) ** 2)))
    print(f"trained {len(model['trees'])} trees in {time.time() - t0:.1f}s; "
          f"in-sample delta RMSE {train_rmse:.4f}", flush=True)

    _sync_shared_code(_extract_shared_code())
    print(f"synced ML_SHARED_CODE into {KERNEL.name}", flush=True)

    model_json = json.dumps(model, separators=(",", ":"))
    print(f"model JSON size: {len(model_json)} bytes", flush=True)
    _write_model_block(SRC_MODULE, model_json)
    _write_model_block(KERNEL, model_json)
    print(f"wrote model block into {SRC_MODULE.name} and {KERNEL.name}", flush=True)


if __name__ == "__main__":
    main()
